//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proagro
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pedido()
        {
            this.pedido_produto = new HashSet<pedido_produto>();
            this.receber = new HashSet<receber>();
        }
    
        public long id { get; set; }
        public System.DateTime data { get; set; }
        public string numero { get; set; }
        public long pessoa { get; set; }
        public long vendedor { get; set; }
        public long vendedor_comissao { get; set; }
        public string observacao { get; set; }
    
        public virtual pessoa pessoa1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pedido_produto> pedido_produto { get; set; }
        public virtual vendedor vendedor1 { get; set; }
        public virtual vendedor vendedor2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<receber> receber { get; set; }
    }
}
