//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proagro
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido_produto
    {
        public long id { get; set; }
        public long pedido { get; set; }
        public long produto { get; set; }
        public decimal valor { get; set; }
        public decimal quantidade { get; set; }
        public decimal quantidade_entregada { get; set; }
        public System.DateTime data_entrega { get; set; }
        public string detalhes_entrega { get; set; }
    
        public virtual pedido pedido1 { get; set; }
        public virtual produto produto1 { get; set; }
    }
}
