//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proagro
{
    using System;
    using System.Collections.Generic;
    
    public partial class preco
    {
        public long produto { get; set; }
        public System.DateTime data { get; set; }
        public decimal valor { get; set; }
    
        public virtual produto produto1 { get; set; }
    }
}
